---
title: "HTML All Layers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include = FALSE}
library(tidyverse) #Standard data analysis package
library(sf) #Allows for the opening and analysis of spatial files 
library(leaflet) #Important for building interactive tmap tools
library(tmap) #Allows for building interactive HTML tools 
library(maptools) #Allows for more advanced map manipulating and other geospatial tools
library(sp) #Allows for manipulating spatial datasets as type Spatial, which is necissary for some wrangling not shown here
library(raster) #Reads in raster data and has some analysis tools
#library(beepr) #Useful for long loading times
library(RColorBrewer) #Good color palettes 
```

```{r, include=FALSE}
tree_prioritization <- st_read(dsn = ".", layer = "geo_export_2e82f388-c013-45a0-bb25-522154013165") %>% 
   st_transform(crs = 4326) #standard WG 84 CRS 

Wallercreek <- st_read(dsn = ".", layer = "WallerCrk") %>% 
   st_transform(crs = 4326) 

Wallercensus <- st_read(dsn = ".", layer = "wallercensus") %>% 
   st_transform(crs = 4326) 
```

```{r}
uhi_palette = c("oldlace", "red4")
tmap_mode("view")
tm_basemap("Esri.WorldImagery")+
  tm_shape(tree_prioritization_uhi)+
  tm_fill("Intensity", alpha = 0.7)+
  tm_legend(title ="Relative Urban Heat Island Intensity by Census Tract")+
  tm_shape(Wallercreek)+
  tm_borders(col = "black", lwd = 1)
```

