---
title: "Urban Forestry Spatial Correlations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include = FALSE, comment=" "}
library(tidyverse) #Standard data analysis package
library(sf) #Allows for the opening and analysis of spatial files 
library(leaflet) #Important for building interactive tmap tools
library(tmap) #Allows for building interactive HTML tools 
library(maptools) #Allows for more advanced map manipulating and other geospatial tools
library(sp) #Allows for manipulating spatial datasets as type Spatial, which is necissary for some wrangling not shown here
library(raster) #Reads in raster data and has some analysis tools
library(beepr) #Useful for long loading times
library(RColorBrewer) #Good color palettes 


```


```{r, include=FALSE}
tree_prioritization <- st_read(dsn = ".", layer = "geo_export_2e82f388-c013-45a0-bb25-522154013165") %>% 
   st_transform(crs = 4326) #standard WG 84 CRS 

Wallercreek <- st_read(dsn = ".", layer = "WallerCrk") %>% 
   st_transform(crs = 4326) 

Wallercensus <- st_read(dsn = ".", layer = "wallercensus") %>% 
   st_transform(crs = 4326) 

plot(tree_prioritization, max.plot= 13) #max.plot will show all of the columns in the new dataset
beep(3)
```



```{r, include=FALSE}

tree_prioritization_uhi = tree_prioritization %>% 
  dplyr::select(uhi) %>% #there is a select function in the sf package, to avoid confusion make sure you specify you want the dplyr version or your html won't knit 
  mutate(Intensity = uhi)

```

```{r, include=FALSE}
#tmap_mode("view")
#tm_basemap("Esri.WorldStreetMap")+
#  tm_shape(tree_prioritization_uhi)+
# tm_fill("Intensity", alpha = 0.6)+
# tm_legend(title ="Relative Urban Heat Island Intensity by Census Tract")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
air_palette = c("orchid4","cornflowerblue")
uhi_palette = c("oldlace", "red4")
tmap_mode("view")
tm_basemap("Esri.WorldImagery")+
  tm_shape(tree_prioritization_uhi)+
  tm_fill("Intensity", alpha = 0.7)+
  tm_legend(title ="Relative Urban Heat Island Intensity by Census Tract")+
  tm_shape(Wallercreek)+
  tm_borders(col = "black", lwd = 1)#+
  #tm_shape(tree_prioritization)+
  #tm_fill("air_qual", palette = air_palette, alpha = 0.7) #To add aditional layers to the tmap file 
#tmap requires you to both load the shape and then say how you want that shape to be represented. As an outline, etc. 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

uhi_plot = ggplot(tree_prioritization_uhi)+
  geom_sf(aes(fill = uhi))+ #Awesome ggplot function that lets you use the ggplot syntax to make maps 
  scale_fill_gradient("Comparitive Intensity", low = "oldlace", high = "red4")+
  labs(x = "", y = "", title = "Comparitive Urban Heat Island of Census \nTracts Based off Land Surface Temperature")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+ #best option for clean maps in ggplot 
  coord_sf(datum=NA) #This gets rid of those annoying lat and lon lines 

uhi_plot
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

mapRange <- c(range(st_coordinates(Wallercreek)[,1]),range(st_coordinates(Wallercreek)[,2])) # this creates a range that only shows the waller creek watershed so I can trim the other maps with it. It's important to trim the existing maps if you're doing comparisions because loading in a new shapefile dataset will rescale the legend and could be deceptive 

uhi_plot_waller = ggplot(tree_prioritization_uhi)+
  geom_sf(aes(fill = uhi))+
  scale_fill_gradient("Comparitive Intensity", low = "oldlace", high = "red4")+
  labs(x = "", y = "", title = "Comparitive Urban Heat Island of Census \nTracts Based off Land Surface Temperature")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA,xlim = mapRange[c(1:2)], ylim = mapRange[c(3:4)]) #This trims the map with the maprange from above

uhi_plot_waller 
```



```{r, include=FALSE}
tree_count = st_read(dsn = ".", layer = "countingtrees") %>% 
   st_transform(crs = 4326)%>% 
  mutate(tree_intensity = tree_sum/shape_area)

tree_count_only = tree_count %>% 
  dplyr::select(fid, uhi, tree_numbe, tree_sum, shape_area, tree_intensity) %>% 
  as.data.frame() 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
tree_plot = ggplot(tree_count)+
  geom_sf(aes(fill = tree_intensity))+
  scale_fill_gradient("Simulated Canopy Intensity", low = "lightyellow", high = "darkgreen", breaks=c(0,9.818678e-07),labels=c("Low","High"))+
  labs(x = "", y = "", title = "Simulated Tree Intensity By Census Tract")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA)
tree_plot
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
tree_plot_waller = ggplot(tree_count)+
  geom_sf(aes(fill = tree_intensity))+
  scale_fill_gradient("Simulated Canopy Intensity", low = "lightyellow", high = "darkgreen", breaks=c(0,9.818678e-07),labels=c("Low","High"))+
  labs(x = "", y = "", title = "Simulated Tree Intensity By Census Tract")+
  geom_sf(data = Wallercreek, 
          fill = "NA", 
          color = "black", 
          size = 1)+
  theme_minimal()+
  coord_sf(datum=NA,xlim = mapRange[c(1:2)], ylim = mapRange[c(3:4)])
tree_plot_waller

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, comment=" "}
#uhi_regress = lm(uhi~tree_intensity, data = tree_count_only)
#summary(uhi_regress)

ggplot(tree_count_only)+
  geom_point(aes(x = tree_intensity,y=uhi))+
  theme_classic()+
  labs(title = "Relationship Between Urban Heat Island and Simulated \nTree Canopy by Austin Census Tract", y = "Comparitive Land Surface Temperature Intensity", x = "Simulated Tree Intensity")+
  geom_smooth(method = "lm", aes(x = tree_intensity,y=uhi))+
  geom_text(x = 7.5e-07, y = 0.25, aes(label = "*** R Squared = 0.28"))+
  scale_x_continuous(breaks=c(min(tree_count_only$tree_intensity), max(tree_count_only$tree_intensity)), labels=c("Low","High"))

```



